### ISSUE TITLE
Commit History

### ISSUE THREAD

**Issue by Choco31415** [Kenny2github/Anorak#2]
Sorry! I thought that would work.

**Comment by Kenny2github** [comment]
Hmm, the history still seems to be there.

**Comment by Choco31415** [comment]
So Pull Requests can't erase history, got it. Either way, I just erased the commit via a direct push. Does this look good?

**Comment by Kenny2github** [comment]
Sorry for the late reply; Direct push seems to have worked! I'm glad i added you as a collaborator 😁
