### ISSUE TITLE
Can't login to wiki with API

### ISSUE THREAD

**Issue by Kenny2github** [Kenny2github/Anorak#3]
The API responds with "Aborted":"Authentication requires user interaction, which is not supported by action=login. To be able to login with action=login, see [[Special:BotPasswords]]. To continue using main-account login, see action=clientlogin." when I use the actual bot account's main account name and password. If I create a bot password and login with MyOwnMainAcc@BotName and the bot password it responds with "Failed":"The supplied credentials could not be authenticated". I don't really know how bot passwords work exactly so what am I doing wrong?

**Comment by Choco31415** [comment]
I guess I hadn't read this after all.

action=login is for MW 1.26 and before. You'll need to use the new action=query&meta=tokens syntax.

What does MyOwnMainAcc@BotName stand for? The @ is confusing.

**Comment by Kenny2github** [comment]
I used action=query&meta=tokens to get the login token, but logging in is the problem.

In [[Special:BotPasswords]] on the wiki, when I generated the password, it said "You can use <my main account name>@<bot account name> and the password <generated bot password> to login, but that gives me the "Failed" message. If I try to log in with the bot account's actual username and password, it gives the "Aborted" message.

**Comment by Choco31415** [comment]
I always forget about that. :p

What custom content is in LocalSettings.php?

By the way, as a last ditch effort, you are welcome to use JavaMediawikiBot.

**Comment by Kenny2github** [comment]
```
wfLoadExtension( 'CharInsert' );
wfLoadExtension( 'Interwiki' );
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['user']['createaccount'] = false;
$wgGroupPermissions['prefect']['createaccount'] = false;
$wgGroupPermissions['teacher']['createaccount'] = true;
$wgGroupPermissions['sysop']['createaccount'] = false;
$wgGroupPermissions['bureaucrat']['createaccount'] = true;
$wgGroupPermissions['prefect']['delete'] = true;
$wgGroupPermissions['prefect']['rollback'] = true;
$wgGroupPermissions['prefect']['patrol'] = true;
$wgGroupPermissions['prefect']['patrolmarks'] = true;
$wgGroupPermissions['teacher']['rollback'] = true;
$wgGroupPermissions['teacher']['patrol'] = true;
$wgGroupPermissions['teacher']['patrolmarks'] = true;
$wgGroupPermissions['teacher']['upload'] = true;
$wgGroupPermissions['user']['upload'] = false;
$wgGroupPermissions['*']['upload'] = false;
$wgGroupPermissions['sysop']['upload'] = false;
$wgGroupPermissions['bureaucrat']['upload'] = true;
define("NS_HKUGA", 3000);
define("NS_HKUGA_TALK", 3001);
define("NS_HKUGAPS", 3002);
define("NS_HKUGAPS_TALK", 3003);
define("NS_HKUGAC", 3004);
define("NS_HKUGAC_TALK", 3005);
$wgExtraNamespaces[NS_HKUGA] = "HKUGA";
$wgExtraNamespaces[NS_HKUGA_TALK] = "HKUGA_talk";
$wgExtraNamespaces[NS_HKUGAPS] = "HKUGAPS";
$wgExtraNamespaces[NS_HKUGAPS_TALK] = "HKUGAPS_talk";
$wgExtraNamespaces[NS_HKUGAC] = "HKUGAC";
$wgExtraNamespaces[NS_HKUGAC_TALK] = "HKUGAC_talk";
# Enable subpages in all namespaces
$wgNamespacesWithSubpages = array_fill(0, 4000, true);
$wgRestrictionLevels[] = 'ITprefect';
$wgGroupPermissions['prefect']['ITprefect'] = true;
$wgGroupPermissions['sysop']['ITprefect'] = true;
$wgGroupPermissions['bureaucrat']['ITprefect'] = true;
$wgGroupPermissions['teacher']['ITprefect'] = true;
$wgGroupPermissions['sysop']['block'] = false;
$wgGroupPermissions['bureaucrat']['block'] = true;
$wgPFEnableStringFunctions = true;
$wgGroupPermissions['bureaucrat']['interwiki'] = true;
$wgGroupPermissions['teacher']['interwiki'] = true;
$wgGroupPermissions['bureaucrat']['elected'] = true;
$wgGroupPermissions['bureaucrat']['deleterevision'] = true;
$wgGroupPermissions['sysop']['deleterevision'] = true;
$wgGroupPermissions['teacher']['deleterevision'] = true;
$wgEnableAPI = true;
$wgEnableWriteAPI = true;
$wgGroupPermissions['sysop']['editinterface'] = false;
$wgGroupPermissions['teacher']['editinterface'] = false;
$wgGroupPermissions['user']['suppressredirect'] = true;
$wgGroupPermissions['*']['createtalk'] = false;
$wgGroupPermissions['*']['createpage'] = false;
$wgGroupPermissions['user']['createtalk'] = true;
$wgGroupPermissions['user']['createpage'] = true;
$wgGroupPermissions['bureaucrat']['editinterface'] = true;
```

**Comment by Choco31415** [comment]
I tested your login code on a MW 1.28 installation with the given LocalSettings, so that's not the issue.

What are you using to host Mediawiki28? Nginx? Apache? Bitnami?

**Comment by Kenny2github** [comment]
Never mind: _I've figured it out!_ It turns out the password for my bot was too short, so the _interaction_ involved in the login was the prompt for me to change the password! So all I have to do is change the password to over 8 characters and I'm fine!
Sorry to have kinda wasted your time on this.

**Comment by Choco31415** [comment]
That's okay. I'm surprised the short password was accepted.

**Comment by Kenny2github** [comment]
I created the account with a too-short password, using a different account. Whenever I would manually log in to the bot account, it would tell me to make a new password but would still let me "skip this step".
