### ISSUE TITLE
After running for a while it bugs out

### ISSUE THREAD

**Issue by Kenny2github** [Kenny2github/Anorak#5]
After running the bot for a while (after it's gone through about 750 or so changes) it bugs out with the error: `ConnectionError('Connection aborted', BadStatusLine("''",))`

Any ideas what's going on?

**Comment by Choco31415** [comment]
Can you post the entire stack of the error message? Normally errors aren't one-liners.

**Comment by Kenny2github** [comment]
I need to sleep now; I'll post it tomorrow.

**Comment by Choco31415** [comment]
Anything yet?

**Comment by Choco31415** [comment]
Idea Kenny. Although links to Discord are not allowed on Scratch, what about on Github?

**Comment by Kenny2github** [comment]
So it appears that I can't reproduce the bug anymore; I think the error was just basically "there's too much going on on this network, I can't handle it". I'll post the error message here if it appears again, of course.

As for Discord, yes! I'd love to come back! It _is_ sad that there's only me; is it okay if I try to invite other people to it using non-Scratch methods (like on a Minecraft server)?

**Comment by Choco31415** [comment]
Yes, as long as they are on the wiki, and you directly know that the person you're inviting is a wikian. Here you go:

https://discord.gg/9RqWpa

**Comment by Kenny2github** [comment]
Thanks! I've joined now. It seems like I can't send messages anywhere, though.

**Comment by Kenny2github** [comment]
Closing

**Comment by Kenny2github** [comment]
It turns out that the problem was simply that my router throttled me after going too long - so "wontfix" is appropriate
